[versions]
ansi-control-sequence-util = "0.4"
ant = "1.10.15"
asciidoctor = "4.0.4"
asciidoctorj = "3.0.1"
commons-io = "2.21.0"
commons-lang = "3.20.0"
exemplar = "1.0.3"
jsoup = "1.22.1"
junit-jupiter = "6.0.3"
junit4 = "4.13.2"
spock = "2.4-groovy-4.0"
tapi = "6.0.1"

[libraries]
ansi-control-sequence-util = { group = "net.rubygrapefruit", name = "ansi-control-sequence-util", version.ref = "ansi-control-sequence-util" }
ant = { group = "org.apache.ant", name = "ant", version.ref = "ant" }
asciidoctor-jvm-convert = { group = "org.asciidoctor.jvm.convert", name = "org.asciidoctor.jvm.convert.gradle.plugin", version.ref = "asciidoctor" }
asciidoctor-gradle-base = { group = "org.asciidoctor", name = "asciidoctor-gradle-base", version.ref = "asciidoctor" }
asciidoctorj = { group = "org.asciidoctor", name = "asciidoctorj", version.ref = "asciidoctorj" }
asciidoctorj-api = { group = "org.asciidoctor", name = "asciidoctorj-api", version.ref = "asciidoctorj" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang" }
exemplar-samples-check = { group = "org.gradle.exemplar", name = "samples-check", version.ref = "exemplar" }
exemplar-samples-discovery = { group = "org.gradle.exemplar", name = "samples-discovery", version.ref = "exemplar" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-jupiter" }
spock-core = { group = "org.spockframework", name = "spock-core", version.ref = "spock" }
tapi = { group = "org.gradle", name = "gradle-tooling-api", version.ref = "tapi" }

[plugins]
publish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
